### ISSUE TITLE
Ripple element deactivates functionality to onPress.

### ISSUE THREAD

**Issue by alexkyse1** [WrathChaos/react-native-apple-card-views#10]
First of all thank you for all your amazing work.

Question, If I do not wrap the card with the ripple component, the button action does work, otherwise the ripple effect is being triggered and does not let take action the card button onPress event.

How it could be arranged?

**Comment by WrathChaos** [comment]
Hello @alexkyse1,
Simply you do not want Ripple effect am I right? Or do you want to get rid of the whole `react-native-material-ripple` dependency? 
If you just want to deactivate the ripple effect, there is a `rippleEnable` prop, I guess. If you want to get rid of the whole Ripple, we need to fork the library and remove the Ripple library.

**Comment by alexkyse1** [comment]
Hey! Sorry for the late response.

I would like to preserve the ripple effect but also make the "GET" button functional. If the ripple element is present I experienced that the GET button is not touchable as the ripple dominates over the child button element.

**Comment by WrathChaos** [comment]
Ripple itself has the button functionality. What exactly do you want?

**Comment by WrathChaos** [comment]
Hello @alexkyse1,
Please check the new version, I removed the Ripple integration. If you still could not solve the problem, let's look at it together :)
