### ISSUE TITLE
Question about source (image)

### ISSUE THREAD

**Issue by LydiaCha** [WrathChaos/react-native-apple-card-views#16]
Hi, I'm not sure if this is an issue but I didn't know how else to contact you!
I'm trying to customise the image on the cards.

For the title, I've successfully managed it with something like:

`largeTitle={item.title}
`

However when it comes to using `source` for the image, it doesn't work quite the same.
I've done the below but it doesn't seem to work:

`source={item.imageUrlPath}`

This might be a 'me' issue as the imageUrlPath is a field in Cloud Firestore that contains an image url referencing an image in Storage. But I just thought to ask if this has anything to do with the source prop.

Thanks!

**Comment by WrathChaos** [comment]
Hello @LydiaCha  :) 
I think you need to set the source as: 

```
source={{uri: item.imageUrlPath}}
```

**Comment by LydiaCha** [comment]
I get an error saying it can't find the variable imageUrlPath. This might be a me issue. Thanks though! If you have any other ideas let me know!

**Comment by WrathChaos** [comment]
Image only accepts a local require path or online URI. There is no other way to put the source into the Image. Debug your `item.imageUrlPath`.

if you have any other questions please feel free to ask :)
