### ISSUE TITLE
Can I customise the colour of the text in the card titles?

### ISSUE THREAD

**Issue by LydiaCha** [WrathChaos/react-native-apple-card-views#17]
If I want some of the cards to display the title in white lettering and some others in black is there a way to do this?
If I change the colour in the library then the styling will be applied to every page containing the apple card component. I was wondering if there's a way to overwrite the colour in specific pages, not in all of them using it.

**Comment by WrathChaos** [comment]
Hello @LydiaCha,

Yes you can change the style with: 
* smallTitleTextStyle
* largeTitleTextStyle
* footnoteTextStyle

You can even change the whole style with these props. Simply put color: "white" and it will change its color.
