### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNAndrow" was not found in the UIManager using expo

### ISSUE THREAD

**Issue by hristowwe** [WrathChaos/react-native-apple-card-views#28]
I am trying to use this lib which is really cool but when i use expo it only ran on my iphone without any problem but on android i got this error
![image](https://user-images.githubusercontent.com/57602380/122563282-af2d3700-d04c-11eb-999a-b757ec3b50be.png)

I think that's because i used expo??
Can it be fixed

**Comment by WrathChaos** [comment]
Hello @hristowwe,
Thank you for using this library and kind words :)

`react-native-androw` is not able to use it with Expo. I can create the Expo branch however, I'm afraid you will lose these types of shadows in Android.

**Comment by hristowwe** [comment]
ok! If you can make that! Ye as i said before for iphone everything works gr8<< good job 🚀🚀🚀
 For android i got issue above. I will wait for new update

**Comment by hristowwe** [comment]
And one more thing. Can it be done like: For android there is no shadow but for iphone to have shadow

**Comment by jmarbutt** [comment]
I am having the same issue, did you make a variation of this?

**Comment by WrathChaos** [comment]
Hey guys,
I am going to make it this weekend. Sorry for the late response. It will be available soon :)

**Comment by hristowwe** [comment]
fixed?

**Comment by WrathChaos** [comment]
Hello guys, 
@jmarbutt, @hristowwe 

Finally, I made the expo version of the library. Please check the documentation :)

[Expo Version](https://github.com/WrathChaos/react-native-apple-card-views#expo-version)

All you need to do is installing from the expo branch and install the new dependency than you're good to go :) 

Please open a new issue, if you need something else :)
