### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by hristowwe** [WrathChaos/react-native-apple-card-views#35]
**Invalid tag name "react-native-apple-card-views#expo": Tags may not have any characters that encodeURIComponent encodes.**
When i ran 
`>npm i react-native-apple-card-views#expo`

**Comment by WrathChaos** [comment]
Hello @hristowwe,
Thank you so much for reporting the issue. 
I'm testing it now.

**Comment by WrathChaos** [comment]
Hello @hristowwe 
I am extremely sorry about the delay. 

[Version 3 🥳](https://github.com/WrathChaos/react-native-apple-card-views/releases/tag/3.0.0) is available with direct Expo support and also removed almost all dependencies :) 

Please try it out!
