### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by hristowwe** [WrathChaos/react-native-apple-card-views#43]
When i ran `npm i react-native-apple-card-views#expo` i got 
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "react-native-apple-card-views#expo" of package "react-native-apple-card-views#expo": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by WrathChaos** [comment]
Hello @hristowwe 
Thank you for reporting this. 
I will fix this asap!

**Comment by WrathChaos** [comment]
Hello @Tiagochicoo, @hristowwe 
I am extremely sorry about the delay. 

[Version 3 🥳](https://github.com/WrathChaos/react-native-apple-card-views/releases/tag/3.0.0) is available with direct Expo support and also removed almost all dependencies :) 

Please try it out!
